class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _translations = {
    // ---- App ----
    'finance_me_local': {
      'en': 'Finance me Local',
      'ar': 'تمويلي المحلي',
      'ru': 'Finance me Local',
      'de': 'Finance me Local',
      'ku': 'Finance me Local',
      'tr': 'Finance me Local',
    },
    'app_subtitle': {
      'en': 'Your Finance, Your Control',
      'ar': 'أموالك، سيطرتك',
      'ru': 'Ваши финансы, ваш контроль',
      'de': 'Ihre Finanzen, Ihre Kontrolle',
      'ku': 'Darayîya te, Kontrola te',
      'tr': 'Finansınız, Kontrolünüz',
    },

    // ---- Tabs ----
    'transactions': {
      'en': 'Transactions',
      'ar': 'المعاملات',
      'ru': 'Транзакции',
      'de': 'Transaktionen',
      'ku': 'Danûstandin',
      'tr': 'İşlemler',
    },
    'subscriptions': {
      'en': 'Subscriptions',
      'ar': 'الاشتراكات',
      'ru': 'Подписки',
      'de': 'Abonnements',
      'ku': 'Abonetî',
      'tr': 'Abonelikler',
    },
    'analytics': {
      'en': 'Analytics',
      'ar': 'التحليلات',
      'ru': 'Аналитика',
      'de': 'Analysen',
      'ku': 'Analîtîk',
      'tr': 'Analizler',
    },

    // ---- Settings ----
    'settings': {
      'en': 'Settings',
      'ar': 'الإعدادات',
      'ru': 'Настройки',
      'de': 'Einstellungen',
      'ku': 'Mîhengan',
      'tr': 'Ayarlar',
    },
    'appearance': {
      'en': 'Appearance',
      'ar': 'المظهر',
      'ru': 'Внешний вид',
      'de': 'Erscheinungsbild',
      'ku': 'Xuyanî',
      'tr': 'Görünüm',
    },
    'theme': {
      'en': 'Theme',
      'ar': 'السمة',
      'ru': 'Тема',
      'de': 'Design',
      'ku': 'Reng',
      'tr': 'Tema',
    },
    'system': {
      'en': 'System',
      'ar': 'النظام',
      'ru': 'Система',
      'de': 'System',
      'ku': 'Pergal',
      'tr': 'Sistem',
    },
    'light': {
      'en': 'Light',
      'ar': 'فاتح',
      'ru': 'Светлая',
      'de': 'Hell',
      'ku': 'Ronahî',
      'tr': 'Aydınlık',
    },
    'dark': {
      'en': 'Dark',
      'ar': 'داكن',
      'ru': 'Тёмная',
      'de': 'Dunkel',
      'ku': 'Tarikî',
      'tr': 'Karanlık',
    },
    'color_palette': {
      'en': 'Color Palette',
      'ar': 'لوحة الألوان',
      'ru': 'Цветовая палитра',
      'de': 'Farbpalette',
      'ku': 'Paleta Rengan',
      'tr': 'Ren Paleti',
    },
    'primary_color': {
      'en': 'Primary Color',
      'ar': 'اللون الأساسي',
      'ru': 'Основной цвет',
      'de': 'Primärfarbe',
      'ku': 'Rengê Seretayî',
      'tr': 'Ana Renk',
    },
    'standard': {
      'en': 'Standard',
      'ar': 'قياسي',
      'ru': 'Стандартная',
      'de': 'Standard',
      'ku': 'Standard',
      'tr': 'Standart',
    },
    'colorblind_safe': {
      'en': 'Colorblind Safe',
      'ar': 'آمن لعمى الألوان',
      'ru': 'Для дальтоников',
      'de': 'Farbenblind-sicher',
      'ku': 'Ji bo Rengkoran',
      'tr': 'Renk Körü Dostu',
    },
    'colorblind_safe_subtitle': {
      'en': 'Use blue/orange palette optimized for colour vision deficiency',
      'ar':
          'استخدم لوحة الألوان الزرقاء/البرتقالية المُحسَّنة لضعف رؤية الألوان',
      'ru': 'Сине-оранжевая палитра, оптимизированная для дальтонизма',
      'de': 'Blau/Orange-Palette für Farbenblindheit optimiert',
      'ku':
          'Paleta şîn/porteqalî ya ji bo kêmasiya dîtina rengan hatiye optimîzekirin',
      'tr': 'Renk görme eksikliği için optimize edilmiş mavi/turuncu palet',
    },
    'ocean_blue': {
      'en': 'Ocean Blue',
      'ar': 'أزرق محيطي',
      'ru': 'Океанский синий',
      'de': 'Ozeanblau',
      'ku': 'Şîna Okyanûsê',
      'tr': 'Okyanus Mavisi',
    },
    'emerald_green': {
      'en': 'Emerald Green',
      'ar': 'أخضر زمردي',
      'ru': 'Изумрудно-зелёный',
      'de': 'Smaragdgrün',
      'ku': 'Keska Zimrûdê',
      'tr': 'Zümrüt Yeşili',
    },
    'amethyst_purple': {
      'en': 'Amethyst Purple',
      'ar': 'بنفسجي جمشتي',
      'ru': 'Аметистовый фиолетовый',
      'de': 'Amethystviolett',
      'ku': 'Morê Ametîst',
      'tr': 'Ametist Moru',
    },
    'sunset_orange': {
      'en': 'Sunset Orange',
      'ar': 'برتقالي الغروب',
      'ru': 'Закатный оранжевый',
      'de': 'Sonnenuntergangsorange',
      'ku': 'Porteqalîya Rojavabûnê',
      'tr': 'Gün Batımı Turuncusu',
    },
    'ruby_red': {
      'en': 'Ruby Red',
      'ar': 'أحمر ياقوتي',
      'ru': 'Рубиново-красный',
      'de': 'Rubinrot',
      'ku': 'Sora Yaqûtê',
      'tr': 'Yakut Kırmızısı',
    },
    'deep_teal': {
      'en': 'Deep Teal',
      'ar': 'أزرق مخضر داكن',
      'ru': 'Глубокий бирюзовый',
      'de': 'Tiefes Türkis',
      'ku': 'Tîlê Kûr',
      'tr': 'Derin Turkuaz',
    },
    'standard_red_green': {
      'en': 'Standard (Red/Green)',
      'ar': 'قياسي (أحمر/أخضر)',
      'ru': 'Стандартная (Красный/Зелёный)',
      'de': 'Standard (Rot/Grün)',
      'ku': 'Standard (Sor/Kesk)',
      'tr': 'Standart (Kırmızı/Yeşil)',
    },
    'colorblind_blue_orange': {
      'en': 'Colorblind Accessible (Blue/Orange)',
      'ar': 'متاح لعمى الألوان (أزرق/برتقالي)',
      'ru': 'Для дальтоников (Синий/Оранжевый)',
      'de': 'Farbenblind-zugänglich (Blau/Orange)',
      'ku': 'Gihîştbar ji bo Rengkoran (Şîn/Porteqalî)',
      'tr': 'Renk Körü Erişilebilir (Mavi/Turuncu)',
    },
    'accessibility': {
      'en': 'Accessibility',
      'ar': 'إمكانية الوصول',
      'ru': 'Специальные возможности',
      'de': 'Barrierefreiheit',
      'ku': 'Gihîştinbarî',
      'tr': 'Erişilebilirlik',
    },
    'accessibility_mode': {
      'en': 'Accessibility Mode',
      'ar': 'وضع إمكانية الوصول',
      'ru': 'Режим доступности',
      'de': 'Barrierefreiheitsmodus',
      'ku': 'Moda Gihîştinbariyê',
      'tr': 'Erişilebilirlik Modu',
    },
    'accessibility_mode_sub': {
      'en': 'Disable animations, effects, and sensory triggers',
      'ar': 'تعطيل الحركات والتأثيرات والمحفزات الحسية',
      'ru': 'Отключить анимации, эффекты и сенсорные триггеры',
      'de': 'Animationen, Effekte und sensorische Auslöser deaktivieren',
      'ku': 'Anîmasyon, tesîr û tetikên hestî neçalak bike',
      'tr':
          'Animasyonları, efektleri ve duyusal tetikleyicileri devre dışı bırak',
    },
    'ambient_background': {
      'en': 'Ambient Background',
      'ar': 'الخلفية المحيطة',
      'ru': 'Фоновый эффект',
      'de': 'Ambient-Hintergrund',
      'ku': 'Paşperdeya Ambîent',
      'tr': 'Ortam Arka Planı',
    },
    'ambient_background_sub': {
      'en': 'Gentle calming background effect',
      'ar': 'تأثير خلفية مهدئ لطيف',
      'ru': 'Мягкий успокаивающий фоновый эффект',
      'de': 'Sanfter beruhigender Hintergrundeffekt',
      'ku': 'Tesîra paşperdeyê ya nerm û aram',
      'tr': 'Hafif sakinleştirici arka plan efekti',
    },
    'security_data': {
      'en': 'Security & Data',
      'ar': 'الأمان والبيانات',
      'ru': 'Безопасность и данные',
      'de': 'Sicherheit & Daten',
      'ku': 'Ewlehî & Dane',
      'tr': 'Güvenlik & Veri',
    },
    'biometric_lock': {
      'en': 'Biometric Lock',
      'ar': 'القفل البيومتري',
      'ru': 'Биометрическая блокировка',
      'de': 'Biometrische Sperre',
      'ku': 'Qefala Biyometrîk',
      'tr': 'Biyometrik Kilit',
    },
    'biometric_active': {
      'en': 'Biometric lock is active',
      'ar': 'القفل البيومتري نشط',
      'ru': 'Биометрическая блокировка активна',
      'de': 'Biometrische Sperre ist aktiv',
      'ku': 'Qefala biyometrîk çalak e',
      'tr': 'Biyometrik kilit aktif',
    },
    'biometric_off': {
      'en': 'Biometric lock is off',
      'ar': 'القفل البيومتري معطّل',
      'ru': 'Биометрическая блокировка отключена',
      'de': 'Biometrische Sperre ist deaktiviert',
      'ku': 'Qefala biyometrîk neçalak e',
      'tr': 'Biyometrik kilit kapalı',
    },
    'language': {
      'en': 'Language',
      'ar': 'اللغة',
      'ru': 'Язык',
      'de': 'Sprache',
      'ku': 'Ziman',
      'tr': 'Dil',
    },
    'english': {
      'en': 'English',
      'ar': 'English',
      'ru': 'English',
      'de': 'English',
      'ku': 'English',
      'tr': 'English',
    },
    'currency': {
      'en': 'Currency',
      'ar': 'العملة',
      'ru': 'Валюта',
      'de': 'Währung',
      'ku': 'Dirav',
      'tr': 'Para Birimi',
    },
    'currency_usd': {
      'en': 'US Dollar',
      'ar': 'دولار أمريكي',
      'ru': 'Доллар США',
      'de': 'US-Dollar',
      'ku': 'Dolarê Amerîkî',
      'tr': 'ABD Doları',
    },
    'currency_eur': {
      'en': 'Euro',
      'ar': 'يورو',
      'ru': 'Евро',
      'de': 'Euro',
      'ku': 'Euro',
      'tr': 'Euro',
    },
    'currency_gbp': {
      'en': 'British Pound',
      'ar': 'جنيه إسترليني',
      'ru': 'Фунт стерлингов',
      'de': 'Britisches Pfund',
      'ku': 'Poundê Brîtanî',
      'tr': 'İngiliz Sterlini',
    },
    'currency_sar': {
      'en': 'Saudi Riyal',
      'ar': 'ريال سعودي',
      'ru': 'Саудовский риал',
      'de': 'Saudi-Riyal',
      'ku': 'Riyalê Siûdî',
      'tr': 'Suudi Riyali',
    },
    'currency_aed': {
      'en': 'UAE Dirham',
      'ar': 'درهم إماراتي',
      'ru': 'Дирхам ОАЭ',
      'de': 'VAE-Dirham',
      'ku': 'Dirhemê Emîran',
      'tr': 'BAE Dirhemi',
    },
    'currency_aud': {
      'en': 'Australian Dollar',
      'ar': 'دولار أسترالي',
      'ru': 'Австралийский доллар',
      'de': 'Australischer Dollar',
      'ku': 'Dolarê Awistralyayê',
      'tr': 'Avustralya Doları',
    },
    'currency_cad': {
      'en': 'Canadian Dollar',
      'ar': 'دولار كندي',
      'ru': 'Канадский доллар',
      'de': 'Kanadischer Dollar',
      'ku': 'Dolarê Kanada',
      'tr': 'Kanada Doları',
    },
    'currency_chf': {
      'en': 'Swiss Franc',
      'ar': 'فرنك سويسري',
      'ru': 'Швейцарский франк',
      'de': 'Schweizer Franken',
      'ku': 'Frankê Swîsreyê',
      'tr': 'İsviçre Frangı',
    },
    'currency_cny': {
      'en': 'Chinese Yuan',
      'ar': 'يوان صيني',
      'ru': 'Китайский юань',
      'de': 'Chinesischer Yuan',
      'ku': 'Yuanê Çînî',
      'tr': 'Çin Yuanı',
    },
    'currency_inr': {
      'en': 'Indian Rupee',
      'ar': 'روبية هندية',
      'ru': 'Индийская рупия',
      'de': 'Indische Rupie',
      'ku': 'Rupiya Hindî',
      'tr': 'Hint Rupisi',
    },
    'currency_jpy': {
      'en': 'Japanese Yen',
      'ar': 'ين ياباني',
      'ru': 'Японская иена',
      'de': 'Japanischer Yen',
      'ku': 'Yenê Japonî',
      'tr': 'Japon Yeni',
    },
    'currency_krw': {
      'en': 'South Korean Won',
      'ar': 'وون كوري جنوبي',
      'ru': 'Южнокорейская вона',
      'de': 'Südkoreanischer Won',
      'ku': 'Wonê Koreya Başûr',
      'tr': 'Güney Kore Wonu',
    },
    'currency_myr': {
      'en': 'Malaysian Ringgit',
      'ar': 'رينغيت ماليزي',
      'ru': 'Малайзийский ринггит',
      'de': 'Malaysischer Ringgit',
      'ku': 'Ringgitê Malezyayê',
      'tr': 'Malezya Ringgiti',
    },
    'currency_rub': {
      'en': 'Russian Ruble',
      'ar': 'روبل روسي',
      'ru': 'Российский рубль',
      'de': 'Russischer Rubel',
      'ku': 'Rubleyê Rûsî',
      'tr': 'Rus Rublesi',
    },
    'currency_sgd': {
      'en': 'Singapore Dollar',
      'ar': 'دولار سنغافوري',
      'ru': 'Сингапурский доллар',
      'de': 'Singapur-Dollar',
      'ku': 'Dolarê Singapurê',
      'tr': 'Singapur Doları',
    },
    'currency_try': {
      'en': 'Turkish Lira',
      'ar': 'ليرة تركية',
      'ru': 'Турецкая лира',
      'de': 'Türkische Lira',
      'ku': 'Lîreyê Tirkî',
      'tr': 'Türk Lirası',
    },

    // ---- Export / Import ----
    'export_encrypted_backup': {
      'en': 'Export Encrypted Backup',
      'ar': 'تصدير نسخة احتياطية مشفرة',
      'ru': 'Экспорт зашифрованной копии',
      'de': 'Verschlüsseltes Backup exportieren',
      'ku': 'Paşgira Şîfrekirî Derke',
      'tr': 'Şifreli Yedek Dışa Aktar',
    },
    'import_encrypted_backup': {
      'en': 'Import Encrypted Backup',
      'ar': 'استيراد نسخة احتياطية مشفرة',
      'ru': 'Импорт зашифрованной копии',
      'de': 'Verschlüsseltes Backup importieren',
      'ku': 'Paşgira Şîfrekirî Bîne',
      'tr': 'Şifreli Yedek İçe Aktar',
    },
    'set_backup_password': {
      'en': 'Set Backup Password',
      'ar': 'تعيين كلمة مرور النسخ الاحتياطي',
      'ru': 'Установить пароль резервной копии',
      'de': 'Backup-Passwort festlegen',
      'ku': 'Şîfreya Paşgirê Saz Bike',
      'tr': 'Yedek Şifresi Belirle',
    },
    'enter_backup_password': {
      'en': 'Enter Backup Password',
      'ar': 'أدخل كلمة مرور النسخ الاحتياطي',
      'ru': 'Введите пароль резервной копии',
      'de': 'Backup-Passwort eingeben',
      'ku': 'Şîfreya Paşgirê Binivîse',
      'tr': 'Yedek Şifresini Gir',
    },
    'password': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'ru': 'Пароль',
      'de': 'Passwort',
      'ku': 'Şîfre',
      'tr': 'Şifre',
    },
    'confirm_password': {
      'en': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'ru': 'Подтвердите пароль',
      'de': 'Passwort bestätigen',
      'ku': 'Şîfreyê Piştrast Bike',
      'tr': 'Şifreyi Onayla',
    },
    'passwords_do_not_match': {
      'en': 'Passwords do not match',
      'ar': 'كلمات المرور غير متطابقة',
      'ru': 'Пароли не совпадают',
      'de': 'Passwörter stimmen nicht überein',
      'ku': 'Şîfre li hev nakin',
      'tr': 'Şifreler eşleşmiyor',
    },
    'password_required': {
      'en': 'Password required',
      'ar': 'كلمة المرور مطلوبة',
      'ru': 'Требуется пароль',
      'de': 'Passwort erforderlich',
      'ku': 'Şîfre pêwîst e',
      'tr': 'Şifre gerekli',
    },
    'cancel': {
      'en': 'Cancel',
      'ar': 'إلغاء',
      'ru': 'Отмена',
      'de': 'Abbrechen',
      'ku': 'Betal',
      'tr': 'İptal',
    },
    'proceed': {
      'en': 'Proceed',
      'ar': 'متابعة',
      'ru': 'Продолжить',
      'de': 'Fortfahren',
      'ku': 'Bidomîne',
      'tr': 'Devam',
    },
    'select_encrypted_backup': {
      'en': 'Select Encrypted Backup',
      'ar': 'اختيار نسخة احتياطية مشفرة',
      'ru': 'Выберите зашифрованную копию',
      'de': 'Verschlüsseltes Backup auswählen',
      'ku': 'Paşgira Şîfrekirî Hilbijêre',
      'tr': 'Şifreli Yedek Seç',
    },
    'invalid_backup_file': {
      'en': 'Invalid or corrupted backup file.',
      'ar': 'ملف النسخ الاحتياطي غير صالح أو تالف.',
      'ru': 'Недействительный или повреждённый файл резервной копии.',
      'de': 'Ungültige oder beschädigte Backup-Datei.',
      'ku': 'Pelê paşgirê nederbasdar an xerabûyî ye.',
      'tr': 'Geçersiz veya bozuk yedek dosyası.',
    },
    'wrong_password_error': {
      'en': 'Wrong password.',
      'ar': 'كلمة مرور خاطئة.',
      'ru': 'Неверный пароль.',
      'de': 'Falsches Passwort.',
      'ku': 'Şîfreya şaş.',
      'tr': 'Yanlış şifre.',
    },
    'corrupt_backup_file': {
      'en': 'Corrupted backup data. The file may be damaged.',
      'ar': 'بيانات النسخة الاحتياطية تالفة. قد يكون الملف معطوباً.',
      'ru': 'Повреждённые данные резервной копии. Возможно файл испорчен.',
      'de': 'Beschädigte Backup-Daten. Die Datei könnte defekt sein.',
      'ku': 'Daneyên paşgirê xerabûyî ne. Dibe ku pel şikestî be.',
      'tr': 'Bozuk yedek verisi. Dosya hasar görmüş olabilir.',
    },
    'backup_saved': {
      'en': 'Backup saved:',
      'ar': 'تم حفظ النسخة الاحتياطية:',
      'ru': 'Резервная копия сохранена:',
      'de': 'Backup gespeichert:',
      'ku': 'Paşgir hat tomarkirin:',
      'tr': 'Yedek kaydedildi:',
    },
    'imported': {
      'en': 'Imported',
      'ar': 'تم استيراد',
      'ru': 'Импортировано',
      'de': 'Importiert',
      'ku': 'Hat anîn',
      'tr': 'İçe aktarıldı',
    },
    'imported_records': {
      'en': 'records successfully',
      'ar': 'سجل بنجاح',
      'ru': 'записей успешно',
      'de': 'Datensätze erfolgreich',
      'ku': 'tomar bi serkeftî',
      'tr': 'kayıt başarıyla',
    },
    'export_cancelled': {
      'en': 'Export cancelled by user.',
      'ar': 'تم إلغاء التصدير.',
      'ru': 'Экспорт отменён пользователем.',
      'de': 'Export vom Benutzer abgebrochen.',
      'ku': 'Derxistin ji hêla bikarhêner ve hat betalkirin.',
      'tr': 'Dışa aktarma kullanıcı tarafından iptal edildi.',
    },
    'import_cancelled': {
      'en': 'Import cancelled by user.',
      'ar': 'تم إلغاء الاستيراد.',
      'ru': 'Импорт отменён пользователем.',
      'de': 'Import vom Benutzer abgebrochen.',
      'ku': 'Anîn ji hêla bikarhêner ve hat betalkirin.',
      'tr': 'İçe aktarma kullanıcı tarafından iptal edildi.',
    },

    // ---- Home Screen ----
    'total_balance': {
      'en': 'Total Balance',
      'ar': 'الرصيد الإجمالي',
      'ru': 'Общий баланс',
      'de': 'Gesamtbilanz',
      'ku': 'Balanseya Giştî',
      'tr': 'Toplam Bakiye',
    },
    'income': {
      'en': 'Income',
      'ar': 'الدخل',
      'ru': 'Доходы',
      'de': 'Einnahmen',
      'ku': 'Dahatin',
      'tr': 'Gelir',
    },
    'expenses': {
      'en': 'Expenses',
      'ar': 'المصروفات',
      'ru': 'Расходы',
      'de': 'Ausgaben',
      'ku': 'Mesref',
      'tr': 'Giderler',
    },
    'monthly_income_label': {
      'en': 'Monthly Income',
      'ar': 'الدخل الشهري',
      'ru': 'Доход за месяц',
      'de': 'Monatliches Einkommen',
      'ku': 'Dahatina Mehane',
      'tr': 'Aylık Gelir',
    },
    'monthly_subs_label': {
      'en': 'Monthly Subs',
      'ar': 'الاشتراكات الشهرية',
      'ru': 'Подписки в месяц',
      'de': 'Monatliche Abos',
      'ku': 'Abonetiyên Mehane',
      'tr': 'Aylık Abonelikler',
    },
    'recurring_items': {
      'en': 'Recurring Items',
      'ar': 'العناصر المتكررة',
      'ru': 'Повторяющиеся',
      'de': 'Wiederkehrende',
      'ku': 'Bûyerên Dubare',
      'tr': 'Tekrarlananlar',
    },
    'no_recurring_income': {
      'en': 'No recurring income added yet.\nTap + on the Home screen to add.',
      'ar': 'لا يوجد دخل متكرر بعد.\nاضغط + في الشاشة الرئيسية للإضافة.',
      'ru': 'Повторяющихся доходов пока нет.\nНажмите + на главном экране.',
      'de':
          'Noch kein wiederkehrendes Einkommen.\nTippe + auf dem Startbildschirm.',
      'ku':
          'Hêj dahatek dubare nehatiye zêdekirin.\nDi ekrana sereke de + bikirtînin.',
      'tr':
          'Henüz tekrarlanan gelir eklenmedi.\nAna ekranda + düğmesine basın.',
    },
    'no_recurring_expenses': {
      'en':
          'No recurring expenses added yet.\nTap + on the Home screen to add.',
      'ar': 'لا توجد مصروفات متكررة بعد.\nاضغط + في الشاشة الرئيسية للإضافة.',
      'ru': 'Повторяющихся расходов пока нет.\nНажмите + на главном экране.',
      'de':
          'Noch keine wiederkehrenden Ausgaben.\nTippe + auf dem Startbildschirm.',
      'ku':
          'Hêj lêçûnên dubare nehatine zêdekirin.\nDi ekrana sereke de + bikirtînin.',
      'tr':
          'Henüz tekrarlanan gider eklenmedi.\nAna ekranda + düğmesine basın.',
    },
    'edit_balance': {
      'en': 'Edit Balance',
      'ar': 'تعديل الرصيد',
      'ru': 'Изменить баланс',
      'de': 'Bilanz bearbeiten',
      'ku': 'Balanseyê Biguherîne',
      'tr': 'Bakiyeyi Düzenle',
    },
    'set_balance_title': {
      'en': 'Set Initial Balance',
      'ar': 'تعيين الرصيد الابتدائي',
      'ru': 'Установить начальный баланс',
      'de': 'Anfangsbilanz festlegen',
      'ku': 'Balanseya Destpêkê Saz Bike',
      'tr': 'Başlangıç Bakiyesini Belirle',
    },
    'balance_hint': {
      'en': 'Enter your current balance',
      'ar': 'أدخل رصيدك الحالي',
      'ru': 'Введите текущий баланс',
      'de': 'Geben Sie Ihren aktuellen Kontostand ein',
      'ku': 'Balanseya xwe ya niha binivîse',
      'tr': 'Mevcut bakiyenizi girin',
    },
    'save': {
      'en': 'Save',
      'ar': 'حفظ',
      'ru': 'Сохранить',
      'de': 'Speichern',
      'ku': 'Tomar',
      'tr': 'Kaydet',
    },
    'no_transactions': {
      'en': 'No transactions yet',
      'ar': 'لا توجد معاملات بعد',
      'ru': 'Пока нет транзакций',
      'de': 'Noch keine Transaktionen',
      'ku': 'Hê danûstandin tune',
      'tr': 'Henüz işlem yok',
    },
    'add_first_transaction': {
      'en': 'Tap Income or Expense above to add your first transaction',
      'ar': 'انقر على الدخل أو المصروفات أعلاه لإضافة أول معاملة',
      'ru': 'Нажмите Доходы или Расходы выше, чтобы добавить первую транзакцию',
      'de': 'Tippen Sie oben auf Einnahmen oder Ausgaben, um Ihre erste Transaktion hinzuzufügen',
      'ku': 'Li jor Dahatin an Mesrefê bitikîne da ku danûstandina xwe ya yekem zêde bikî',
      'tr': 'İlk işleminizi eklemek için yukarıdaki Gelir veya Gider\'e dokunun',
    },
    'no_subscriptions': {
      'en': 'No subscriptions yet',
      'ar': 'لا توجد اشتراكات بعد',
      'ru': 'Пока нет подписок',
      'de': 'Noch keine Abonnements',
      'ku': 'Hê abonetî tune',
      'tr': 'Henüz abonelik yok',
    },
    'add_first_subscription': {
      'en': 'Add your first recurring item to get started',
      'ar': 'أضف أول عنصر متكرر للبدء',
      'ru': 'Добавьте первый повторяющийся элемент, чтобы начать',
      'de': 'Fügen Sie Ihr erstes wiederkehrendes Element hinzu, um zu beginnen',
      'ku': 'Ji bo destpêkirinê bûyera xwe ya yekem a dubare zêde bike',
      'tr': 'Başlamak için ilk tekrarlanan öğenizi ekleyin',
    },
    'edit': {
      'en': 'Edit',
      'ar': 'تعديل',
      'ru': 'Изменить',
      'de': 'Bearbeiten',
      'ku': 'Biguherîne',
      'tr': 'Düzenle',
    },
    'delete': {
      'en': 'Delete',
      'ar': 'حذف',
      'ru': 'Удалить',
      'de': 'Löschen',
      'ku': 'Jê bibe',
      'tr': 'Sil',
    },
    'delete_record': {
      'en': 'Delete Record',
      'ar': 'حذف السجل',
      'ru': 'Удалить запись',
      'de': 'Datensatz löschen',
      'ku': 'Tomarê Jê Bibe',
      'tr': 'Kaydı Sil',
    },
    'delete_confirm': {
      'en': 'Are you sure you want to delete',
      'ar': 'هل أنت متأكد من حذف',
      'ru': 'Вы уверены, что хотите удалить',
      'de': 'Sind Sie sicher, dass Sie löschen möchten',
      'ku': 'Tu piştrast î ku dixwazî jê bibî',
      'tr': 'Silmek istediğinizden emin misiniz',
    },
    'delete_confirm_subtitle': {
      'en': 'This cannot be undone.',
      'ar': 'لا يمكن التراجع عن هذا.',
      'ru': 'Это действие нельзя отменить.',
      'de': 'Dies kann nicht rückgängig gemacht werden.',
      'ku': 'Ev nayê vegerandin.',
      'tr': 'Bu işlem geri alınamaz.',
    },

    // ---- Transaction Form ----
    'add_transaction': {
      'en': 'Add Transaction',
      'ar': 'إضافة معاملة',
      'ru': 'Добавить транзакцию',
      'de': 'Transaktion hinzufügen',
      'ku': 'Danûstandinê Zêde Bike',
      'tr': 'İşlem Ekle',
    },
    'edit_transaction': {
      'en': 'Edit Transaction',
      'ar': 'تعديل المعاملة',
      'ru': 'Изменить транзакцию',
      'de': 'Transaktion bearbeiten',
      'ku': 'Danûstandinê Biguherîne',
      'tr': 'İşlemi Düzenle',
    },
    'title': {
      'en': 'Title',
      'ar': 'العنوان',
      'ru': 'Название',
      'de': 'Titel',
      'ku': 'Sernav',
      'tr': 'Başlık',
    },
    'amount': {
      'en': 'Amount',
      'ar': 'المبلغ',
      'ru': 'Сумма',
      'de': 'Betrag',
      'ku': 'Hejmar',
      'tr': 'Tutar',
    },
    'date': {
      'en': 'Date',
      'ar': 'التاريخ',
      'ru': 'Дата',
      'de': 'Datum',
      'ku': 'Dîrok',
      'tr': 'Tarih',
    },
    'expense': {
      'en': 'Expense',
      'ar': 'مصروف',
      'ru': 'Расход',
      'de': 'Ausgabe',
      'ku': 'Mesref',
      'tr': 'Gider',
    },
    'save_transaction': {
      'en': 'Save Transaction',
      'ar': 'حفظ المعاملة',
      'ru': 'Сохранить транзакцию',
      'de': 'Transaktion speichern',
      'ku': 'Danûstandinê Tomar Bike',
      'tr': 'İşlemi Kaydet',
    },
    'update_transaction': {
      'en': 'Update Transaction',
      'ar': 'تحديث المعاملة',
      'ru': 'Обновить транзакцию',
      'de': 'Transaktion aktualisieren',
      'ku': 'Danûstandinê Rojane Bike',
      'tr': 'İşlemi Güncelle',
    },
    'monthly_recurring': {
      'en': 'Monthly Recurring',
      'ar': 'شهري متكرر',
      'ru': 'Ежемесячно повторяющийся',
      'de': 'Monatlich wiederkehrend',
      'ku': 'Mehane Dubare',
      'tr': 'Aylık Yinelenen',
    },
    'monthly_recurring_subtitle': {
      'en': 'Automatically re-add this income at the start of each month',
      'ar': 'إعادة إضافة هذا الدخل تلقائياً في بداية كل شهر',
      'ru': 'Автоматически добавлять этот доход в начале каждого месяца',
      'de':
          'Dieses Einkommen automatisch zu Beginn jedes Monats erneut hinzufügen',
      'ku': 'Vê dahatê di serê her mehê de bixweber ji nû ve zêde bike',
      'tr': 'Bu geliri her ayın başında otomatik olarak yeniden ekleyin',
    },
    'monthly_subscription': {
      'en': 'Monthly Subscription / Recurring',
      'ar': 'اشتراك شهري / دفع دوري',
      'ru': 'Ежемесячная подписка / Повторяющаяся',
      'de': 'Monatliches Abo / Wiederkehrend',
      'ku': 'Abonetiya Mehane / Dubare',
      'tr': 'Aylık Abonelik / Yinelenen',
    },
    'monthly_subscription_subtitle': {
      'en': 'Mark this expense as a recurring monthly subscription',
      'ar': 'حدد هذه المصروفات كاشتراك شهري متكرر',
      'ru': 'Отметить этот расход как ежемесячную подписку',
      'de': 'Diese Ausgabe als monatliches Abo markieren',
      'ku': 'Vê mesrefê wekî abonetiyeke mehane ya dubare nîşan bike',
      'tr': 'Bu gideri aylık yinelenen abonelik olarak işaretle',
    },
    'recurring_income': {
      'en': 'Recurring Income',
      'ar': 'الدخل المتكرر',
      'ru': 'Повторяющийся доход',
      'de': 'Wiederkehrendes Einkommen',
      'ku': 'Dahatina Dubare',
      'tr': 'Yinelenen Gelir',
    },
    'recurring_expenses': {
      'en': 'Recurring Expenses',
      'ar': 'المصروفات المتكررة',
      'ru': 'Повторяющиеся расходы',
      'de': 'Wiederkehrende Ausgaben',
      'ku': 'Mesrefên Dubare',
      'tr': 'Yinelenen Giderler',
    },

    // ---- Subscription Form ----
    'add_subscription': {
      'en': 'Add Subscription',
      'ar': 'إضافة اشتراك',
      'ru': 'Добавить подписку',
      'de': 'Abonnement hinzufügen',
      'ku': 'Abonetiyê Zêde Bike',
      'tr': 'Abonelik Ekle',
    },
    'edit_subscription': {
      'en': 'Edit Subscription',
      'ar': 'تعديل الاشتراك',
      'ru': 'Изменить подписку',
      'de': 'Abonnement bearbeiten',
      'ku': 'Abonetiyê Biguherîne',
      'tr': 'Aboneliği Düzenle',
    },
    'edit_income': {
      'en': 'Edit Income',
      'ar': 'تعديل الدخل',
      'ru': 'Изменить доход',
      'de': 'Einnahme bearbeiten',
      'ku': 'Dahatinê Biguherîne',
      'tr': 'Geliri Düzenle',
    },
    'next_billing_date': {
      'en': 'Next Billing Date',
      'ar': 'تاريخ الفوترة التالي',
      'ru': 'Следующая дата оплаты',
      'de': 'Nächstes Abrechnungsdatum',
      'ku': 'Dîroka Fatureya Pêşî',
      'tr': 'Sonraki Fatura Tarihi',
    },
    'billing_cycle': {
      'en': 'Billing Cycle',
      'ar': 'دورة الفوترة',
      'ru': 'Цикл оплаты',
      'de': 'Abrechnungszyklus',
      'ku': 'Çerxa Fatureyê',
      'tr': 'Fatura Döngüsü',
    },
    'weekly': {
      'en': 'Weekly',
      'ar': 'أسبوعي',
      'ru': 'Еженедельно',
      'de': 'Wöchentlich',
      'ku': 'Heftane',
      'tr': 'Haftalık',
    },
    'bi_weekly': {
      'en': 'Bi-Weekly',
      'ar': 'كل أسبوعين',
      'ru': 'Раз в две недели',
      'de': 'Zweiwöchentlich',
      'ku': 'Du-heftane',
      'tr': 'İki Haftada Bir',
    },
    'monthly': {
      'en': 'Monthly',
      'ar': 'شهري',
      'ru': 'Ежемесячно',
      'de': 'Monatlich',
      'ku': 'Mehane',
      'tr': 'Aylık',
    },
    'yearly': {
      'en': 'Yearly',
      'ar': 'سنوي',
      'ru': 'Ежегодно',
      'de': 'Jährlich',
      'ku': 'Salane',
      'tr': 'Yıllık',
    },
    'every_3_weeks': {
      'en': 'Every 3 Weeks',
      'ar': 'كل ثلاثة أسابيع',
      'ru': 'Каждые 3 недели',
      'de': 'Alle 3 Wochen',
      'ku': 'Her 3 hefte',
      'tr': 'Her 3 Haftada',
    },
    'every_3_months': {
      'en': 'Every 3 Months',
      'ar': 'كل ثلاثة أشهر',
      'ru': 'Каждые 3 месяца',
      'de': 'Alle 3 Monate',
      'ku': 'Her 3 mehan',
      'tr': 'Her 3 Ayda',
    },
    'every_6_months': {
      'en': 'Every 6 Months',
      'ar': 'كل ستة أشهر',
      'ru': 'Каждые 6 месяцев',
      'de': 'Alle 6 Monate',
      'ku': 'Her 6 mehan',
      'tr': 'Her 6 Ayda',
    },
    'every_9_months': {
      'en': 'Every 9 Months',
      'ar': 'كل تسعة أشهر',
      'ru': 'Каждые 9 месяцев',
      'de': 'Alle 9 Monate',
      'ku': 'Her 9 mehan',
      'tr': 'Her 9 Ayda',
    },
    'remind_before_billing': {
      'en': 'Remind me 1 day before billing',
      'ar': 'ذكرني قبل يوم من الفوترة',
      'ru': 'Напомнить за 1 день до оплаты',
      'de': '1 Tag vor Abrechnung erinnern',
      'ku': '1 roj berî fatureyê bîne bîra min',
      'tr': 'Faturadan 1 gün önce hatırlat',
    },
    'save_subscription': {
      'en': 'Save Subscription',
      'ar': 'حفظ الاشتراك',
      'ru': 'Сохранить подписку',
      'de': 'Abonnement speichern',
      'ku': 'Abonetiyê Tomar Bike',
      'tr': 'Aboneliği Kaydet',
    },
    'update_subscription': {
      'en': 'Update Subscription',
      'ar': 'تحديث الاشتراك',
      'ru': 'Обновить подписку',
      'de': 'Abonnement aktualisieren',
      'ku': 'Abonetiyê Rojane Bike',
      'tr': 'Aboneliği Güncelle',
    },
    'add_recurring': {
      'en': 'Add Recurring Item',
      'ar': 'إضافة عنصر متكرر',
      'ru': 'Добавить повторяющееся',
      'de': 'Wiederkehrendes Element hinzufügen',
      'ku': 'Bûyera Dubare Zêde Bike',
      'tr': 'Tekrarlanan Öğe Ekle',
    },
    'edit_recurring': {
      'en': 'Edit Recurring Item',
      'ar': 'تعديل العنصر المتكرر',
      'ru': 'Изменить повторяющееся',
      'de': 'Wiederkehrendes Element bearbeiten',
      'ku': 'Bûyera Dubare Biguherîne',
      'tr': 'Tekrarlanan Öğeyi Düzenle',
    },
    'save_recurring': {
      'en': 'Save',
      'ar': 'حفظ',
      'ru': 'Сохранить',
      'de': 'Speichern',
      'ku': 'Tomar',
      'tr': 'Kaydet',
    },
    'recurring_name': {
      'en': 'Name',
      'ar': 'الاسم',
      'ru': 'Название',
      'de': 'Name',
      'ku': 'Nav',
      'tr': 'İsim',
    },
    'recurring_name_hint': {
      'en': 'e.g. Netflix, Salary',
      'ar': 'مثال: نتفلكس، راتب',
      'ru': 'напр. Netflix, Зарплата',
      'de': 'z.B. Netflix, Gehalt',
      'ku': 'mînak: Netflix, Muçe',
      'tr': 'örn. Netflix, Maaş',
    },
    'start_date': {
      'en': 'First Due Date',
      'ar': 'تاريخ الاستحقاق الأول',
      'ru': 'Первая дата оплаты',
      'de': 'Erstes Fälligkeitsdatum',
      'ku': 'Dîroka Mueyeta Pêşî',
      'tr': 'İlk Vade Tarihi',
    },
    'pause': {
      'en': 'Paused',
      'ar': 'إيقاف مؤقت',
      'ru': 'Приостановлено',
      'de': 'Pausiert',
      'ku': 'Rawestandî',
      'tr': 'Duraklatıldı',
    },
    'active': {
      'en': 'Active',
      'ar': 'نشط',
      'ru': 'Активно',
      'de': 'Aktiv',
      'ku': 'Çalak',
      'tr': 'Aktif',
    },
    'notify_before': {
      'en': 'Remind 1 day before due date',
      'ar': 'تذكير قبل يوم من الاستحقاق',
      'ru': 'Напомнить за 1 день',
      'de': '1 Tag vorher erinnern',
      'ku': '1 roj berî mueyetê bîne bîra min',
      'tr': 'Vadeden 1 gün önce hatırlat',
    },
    'next_due': {
      'en': 'Next:',
      'ar': 'التالي:',
      'ru': 'След.:',
      'de': 'Nächste:',
      'ku': 'Pêşî:',
      'tr': 'Sonraki:',
    },
    'income_type': {
      'en': 'Income',
      'ar': 'دخل',
      'ru': 'Доход',
      'de': 'Einnahme',
      'ku': 'Dahatin',
      'tr': 'Gelir',
    },
    'expense_type': {
      'en': 'Expense',
      'ar': 'مصروف',
      'ru': 'Расход',
      'de': 'Ausgabe',
      'ku': 'Mesref',
      'tr': 'Gider',
    },
    'delete_recurring_confirm': {
      'en': 'Delete this recurring item?',
      'ar': 'حذف هذا العنصر المتكرر؟',
      'ru': 'Удалить этот повторяющийся элемент?',
      'de': 'Dieses wiederkehrende Element löschen?',
      'ku': 'Ev bûyera dubare jê bibin?',
      'tr': 'Bu tekrarlanan öğe silinsin mi?',
    },
    'resume_tooltip': {
      'en': 'Resume',
      'ar': 'استئناف',
      'ru': 'Возобновить',
      'de': 'Fortsetzen',
      'ku': 'Bidomîne',
      'tr': 'Devam Et',
    },
    'pause_tooltip': {
      'en': 'Pause',
      'ar': 'إيقاف مؤقت',
      'ru': 'Приостановить',
      'de': 'Pausieren',
      'ku': 'Rawestîne',
      'tr': 'Duraklat',
    },

    // ---- Validation ----
    'required': {
      'en': 'Required',
      'ar': 'مطلوب',
      'ru': 'Обязательно',
      'de': 'Erforderlich',
      'ku': 'Pêwîst',
      'tr': 'Zorunlu',
    },
    'enter_valid_amount': {
      'en': 'Enter a valid amount',
      'ar': 'أدخل مبلغاً صحيحاً',
      'ru': 'Введите корректную сумму',
      'de': 'Gültigen Betrag eingeben',
      'ku': 'Hejmareke derbasdar binivîse',
      'tr': 'Geçerli bir tutar girin',
    },
    'enter_valid_balance': {
      'en': 'Enter a valid balance',
      'ar': 'أدخل رصيداً صحيحاً',
      'ru': 'Введите корректный баланс',
      'de': 'Gültigen Kontostand eingeben',
      'ku': 'Balanseyeke derbasdar binivîse',
      'tr': 'Geçerli bir bakiye girin',
    },

    // ---- Analytics ----
    'chart_weekly_title': {
      'en': 'Income vs Expenses (Last 7 Days)',
      'ar': 'الدخل مقابل المصروفات (آخر 7 أيام)',
      'ru': 'Доходы и Расходы (Последние 7 дней)',
      'de': 'Einnahmen vs Ausgaben (Letzte 7 Tage)',
      'ku': 'Dahatin li hember Mesref (7 Rojên Dawî)',
      'tr': 'Gelir ve Giderler (Son 7 Gün)',
    },
    'chart_distribution_title': {
      'en': 'Income vs Expenses Distribution',
      'ar': 'توزيع الدخل مقابل المصروفات',
      'ru': 'Распределение доходов и расходов',
      'de': 'Verteilung Einnahmen vs Ausgaben',
      'ku': 'Belavkirina Dahatin li hember Mesref',
      'tr': 'Gelir ve Gider Dağılımı',
    },
    'net_label': {
      'en': 'Net',
      'ar': 'الصافي',
      'ru': 'Итого',
      'de': 'Netto',
      'ku': 'Net',
      'tr': 'Net',
    },
    'transactions_count': {
      'en': 'Transactions',
      'ar': 'المعاملات',
      'ru': 'Транзакции',
      'de': 'Transaktionen',
      'ku': 'Danûstandin',
      'tr': 'İşlemler',
    },
    'income_label': {
      'en': 'Income',
      'ar': 'دخل',
      'ru': 'Доходы',
      'de': 'Einnahmen',
      'ku': 'Dahatin',
      'tr': 'Gelir',
    },
    'expenses_label': {
      'en': 'Expenses',
      'ar': 'مصروفات',
      'ru': 'Расходы',
      'de': 'Ausgaben',
      'ku': 'Mesref',
      'tr': 'Giderler',
    },
    'income_tooltip': {
      'en': 'Income',
      'ar': 'دخل',
      'ru': 'Доходы',
      'de': 'Einnahmen',
      'ku': 'Dahatin',
      'tr': 'Gelir',
    },
    'expenses_tooltip': {
      'en': 'Expenses',
      'ar': 'مصروفات',
      'ru': 'Расходы',
      'de': 'Ausgaben',
      'ku': 'Mesref',
      'tr': 'Giderler',
    },
    'not_enough_data': {
      'en': 'Not enough data',
      'ar': 'بيانات غير كافية',
      'ru': 'Недостаточно данных',
      'de': 'Nicht genügend Daten',
      'ku': 'Daneyên têr nîn in',
      'tr': 'Yeterli veri yok',
    },
    'add_transactions_for_analytics': {
      'en': 'Add at least 2 transactions to see analytics',
      'ar': 'أضف معاملتين على الأقل لعرض التحليلات',
      'ru': 'Добавьте минимум 2 транзакции для просмотра аналитики',
      'de': 'Fügen Sie mindestens 2 Transaktionen hinzu, um Analysen zu sehen',
      'ku': 'Herî kêm 2 danûstandin zêde bike ji bo dîtina analîtîkan',
      'tr': 'Analizleri görmek için en az 2 işlem ekleyin',
    },
    'expenses_by_category': {
      'en': 'Expenses by Category',
      'ar': 'المصروفات حسب الفئة',
      'ru': 'Расходы по категориям',
      'de': 'Ausgaben nach Kategorie',
      'ku': 'Mesref li gorî Kategorî',
      'tr': 'Kategoriye Göre Giderler',
    },
    'income_vs_expenses': {
      'en': 'Income vs Expenses',
      'ar': 'الدخل مقابل المصروفات',
      'ru': 'Доходы и Расходы',
      'de': 'Einnahmen vs Ausgaben',
      'ku': 'Dahatin li hember Mesref',
      'tr': 'Gelir ve Giderler',
    },
    'no_data': {
      'en': 'No data to display',
      'ar': 'لا توجد بيانات للعرض',
      'ru': 'Нет данных для отображения',
      'de': 'Keine Daten vorhanden',
      'ku': 'Daneyên nîşandanê tune',
      'tr': 'Görüntülenecek veri yok',
    },
    'add_transactions_to_see': {
      'en': 'Add transactions to see your analytics',
      'ar': 'أضف معاملات لعرض تحليلاتك',
      'ru': 'Добавьте транзакции, чтобы увидеть аналитику',
      'de': 'Fügen Sie Transaktionen hinzu, um Ihre Analysen zu sehen',
      'ku': 'Danûstandinan zêde bike da ku analîtîkên xwe bibînî',
      'tr': 'Analizlerinizi görmek için işlem ekleyin',
    },

    // ---- Lock Screen ----
    'welcome_back': {
      'en': 'Welcome back',
      'ar': 'مرحباً بعودتك',
      'ru': 'С возвращением',
      'de': 'Willkommen zurück',
      'ku': 'Tu bi xêr hatî',
      'tr': 'Tekrar hoş geldiniz',
    },
    'unlock': {
      'en': 'Unlock',
      'ar': 'فتح',
      'ru': 'Разблокировать',
      'de': 'Entsperren',
      'ku': 'Veke',
      'tr': 'Kilidi Aç',
    },
    'biometric_prompt': {
      'en': 'Authenticate to continue',
      'ar': 'تحقق للمتابعة',
      'ru': 'Авторизуйтесь для продолжения',
      'de': 'Authentifizieren, um fortzufahren',
      'ku': 'Ji bo dewamê piştrast bike',
      'tr': 'Devam etmek için kimlik doğrulayın',
    },

    // ---- Form hints ----
    'title_hint_transaction': {
      'en': 'e.g. Groceries',
      'ar': 'مثال: بقالة',
      'ru': 'напр. Продукты',
      'de': 'z.B. Lebensmittel',
      'ku': 'mînak: Xwarin',
      'tr': 'örn. Market',
    },
    'title_hint_subscription': {
      'en': 'e.g. Netflix',
      'ar': 'مثال: نتفلكس',
      'ru': 'напр. Netflix',
      'de': 'z.B. Netflix',
      'ku': 'mînak: Netflix',
      'tr': 'örn. Netflix',
    },

    // ---- Customization ----
    'customization': {
      'en': 'Customization',
      'ar': 'التخصيص',
      'ru': 'Настройка',
      'de': 'Anpassung',
      'ku': 'Xweserkirin',
      'tr': 'Kişiselleştirme',
    },
    'customization_subtitle': {
      'en': 'Theme, colors, background, and more',
      'ar': 'السمة والألوان والخلفية والمزيد',
      'ru': 'Тема, цвета, фон и другое',
      'de': 'Design, Farben, Hintergrund und mehr',
      'ku': 'Reng, reng, paşperde û bêtir',
      'tr': 'Tema, renkler, arka plan ve daha fazlası',
    },
    'amoled_mode': {
      'en': 'AMOLED Mode',
      'ar': 'وضع AMOLED',
      'ru': 'Режим AMOLED',
      'de': 'AMOLED-Modus',
      'ku': 'Moda AMOLED',
      'tr': 'AMOLED Modu',
    },
    'amoled_mode_sub': {
      'en': 'Pure black background for OLED screens',
      'ar': 'خلفية سوداء خالصة لشاشات OLED',
      'ru': 'Чисто чёрный фон для OLED-экранов',
      'de': 'Rein schwarzer Hintergrund für OLED-Bildschirme',
      'ku': 'Paşperdeya reş a saf ji bo ekranên OLED',
      'tr': 'OLED ekranlar için saf siyah arka plan',
    },
    'accent_gold': {
      'en': 'Gold',
      'ar': 'ذهبي',
      'ru': 'Золотой',
      'de': 'Gold',
      'ku': 'Zêrîn',
      'tr': 'Altın',
    },
    'accent_pink': {
      'en': 'Pink',
      'ar': 'وردي',
      'ru': 'Розовый',
      'de': 'Rosa',
      'ku': 'Pembe',
      'tr': 'Pembe',
    },
    'accent_cyan': {
      'en': 'Cyan',
      'ar': 'سماوي',
      'ru': 'Голубой',
      'de': 'Cyan',
      'ku': 'Seman',
      'tr': 'Camgöbeği',
    },
    'accent_gray': {
      'en': 'Gray',
      'ar': 'رمادي',
      'ru': 'Серый',
      'de': 'Grau',
      'ku': 'Gewr',
      'tr': 'Gri',
    },
    'accent_yellow': {
      'en': 'Yellow',
      'ar': 'أصفر',
      'ru': 'Жёлтый',
      'de': 'Gelb',
      'ku': 'Zer',
      'tr': 'Sarı',
    },
    'accent_olive': {
      'en': 'Olive',
      'ar': 'زيتوني',
      'ru': 'Оливковый',
      'de': 'Oliv',
      'ku': 'Zeytûnî',
      'tr': 'Zeytuni',
    },
    'accent_white': {
      'en': 'White',
      'ar': 'أبيض',
      'ru': 'Белый',
      'de': 'Weiß',
      'ku': 'Spî',
      'tr': 'Beyaz',
    },
    'custom_background': {
      'en': 'Custom Background',
      'ar': 'خلفية مخصصة',
      'ru': 'Пользовательский фон',
      'de': 'Benutzerdefinierter Hintergrund',
      'ku': 'Paşperdeya Xweser',
      'tr': 'Özel Arka Plan',
    },
    'custom_background_sub': {
      'en': 'Set a custom image as background',
      'ar': 'تعيين صورة مخصصة كخلفية',
      'ru': 'Установить своё изображение как фон',
      'de': 'Ein eigenes Bild als Hintergrund festlegen',
      'ku': 'Wêneyek xweser wekî paşperdeyê saz bike',
      'tr': 'Arka plan olarak özel bir resim ayarla',
    },
    'choose_image': {
      'en': 'Choose Image',
      'ar': 'اختر صورة',
      'ru': 'Выбрать изображение',
      'de': 'Bild auswählen',
      'ku': 'Wêne Hilbijêre',
      'tr': 'Resim Seç',
    },
    'overlay_opacity': {
      'en': 'Overlay Opacity',
      'ar': 'عتامة الطبقة',
      'ru': 'Непрозрачность наложения',
      'de': 'Overlay-Deckkraft',
      'ku': 'Zelaliya Qatê',
      'tr': 'Katman Opaklığı',
    },
    'font_size': {
      'en': 'Font Size',
      'ar': 'حجم الخط',
      'ru': 'Размер шрифта',
      'de': 'Schriftgröße',
      'ku': 'Mezinahiya Tîpê',
      'tr': 'Yazı Boyutu',
    },
    'font_small': {
      'en': 'Small',
      'ar': 'صغير',
      'ru': 'Маленький',
      'de': 'Klein',
      'ku': 'Biçûk',
      'tr': 'Küçük',
    },
    'font_medium': {
      'en': 'Medium',
      'ar': 'متوسط',
      'ru': 'Средний',
      'de': 'Mittel',
      'ku': 'Navîn',
      'tr': 'Orta',
    },
    'font_large': {
      'en': 'Large',
      'ar': 'كبير',
      'ru': 'Большой',
      'de': 'Groß',
      'ku': 'Mezin',
      'tr': 'Büyük',
    },
    'home_screen_customization': {
      'en': 'Home Screen',
      'ar': 'الشاشة الرئيسية',
      'ru': 'Главный экран',
      'de': 'Startbildschirm',
      'ku': 'Ekrana Sereke',
      'tr': 'Ana Ekran',
    },
    'show_income_expense': {
      'en': 'Income & Expense Row',
      'ar': 'صف الدخل والمصروفات',
      'ru': 'Строка доходов и расходов',
      'de': 'Einnahmen- & Ausgabenzeile',
      'ku': 'Rêza Dahatin û Mesrefan',
      'tr': 'Gelir ve Gider Satırı',
    },
    'show_recurring': {
      'en': 'Recurring Row',
      'ar': 'صف المتكررات',
      'ru': 'Строка повторяющихся',
      'de': 'Wiederkehrende Zeile',
      'ku': 'Rêza Dubareyan',
      'tr': 'Tekrarlanan Satırı',
    },
    'custom_currency': {
      'en': 'Currency Symbol',
      'ar': 'رمز العملة',
      'ru': 'Символ валюты',
      'de': 'Währungssymbol',
      'ku': 'Sembola Dirav',
      'tr': 'Para Birimi Sembolü',
    },
    'currency_position': {
      'en': 'Symbol Position',
      'ar': 'موضع الرمز',
      'ru': 'Позиция символа',
      'de': 'Symbolposition',
      'ku': 'Cihê Sembolê',
      'tr': 'Sembol Konumu',
    },
    'currency_position_left': {
      'en': 'Left (€50)',
      'ar': 'يسار (€50)',
      'ru': 'Слева (€50)',
      'de': 'Links (€50)',
      'ku': 'Çep (€50)',
      'tr': 'Sol (€50)',
    },
    'currency_position_right': {
      'en': 'Right (50€)',
      'ar': 'يمين (50€)',
      'ru': 'Справа (50€)',
      'de': 'Rechts (50€)',
      'ku': 'Rast (50€)',
      'tr': 'Sağ (50€)',
    },
    'recurring': {
      'en': 'Recurring',
      'ar': 'متكررات',
      'ru': 'Повторяющиеся',
      'de': 'Wiederkehrend',
      'ku': 'Dubare',
      'tr': 'Tekrarlanan',
    },
    'unlocking': {
      'en': 'Unlocking...',
      'ar': 'جاري الفتح...',
      'ru': 'Разблокировка...',
      'de': 'Entsperren...',
      'ku': 'Vekirin...',
      'tr': 'Kilit açılıyor...',
    },
    'background_color': {
      'en': 'Background Color',
      'ar': 'لون الخلفية',
      'ru': 'Цвет фона',
      'de': 'Hintergrundfarbe',
      'ku': 'Rengê Paşîn',
      'tr': 'Arka Plan Rengi',
    },
    'default_gradient': {
      'en': 'Default Gradient',
      'ar': 'التدرج الافتراضي',
      'ru': 'Градиент по умолчанию',
      'de': 'Standardverlauf',
      'ku': 'Gradienta Standard',
      'tr': 'Varsayılan Gradyan',
    },
  };

  static String get(String key, String languageCode) {
    final entry = _translations[key];
    if (entry == null) return key;
    return entry[languageCode] ?? entry['en'] ?? key;
  }
}
